Floor token swap result
DeFiCh/ain pull request #1023
Opened 2022-01-05 09:54 UTC by bvbfan

/kind fix

2022-01-05 16:32 UTC, uzyn approved these changes

2022-01-05 16:34 UTC, uzyn requested changes

2022-01-05 16:34 UTC, uzyn commented on src/masternodes/poolpairs.cpp
> +    if (height >= Params().GetConsensus().FortCanningHillHeight && result > 0) {
This should be done at `slopeSwap()` and not outside of it - which then creates inconsistencies on the outcome.

2022-01-08 06:42 UTC, prasannavl approved these changes

2022-01-11 15:25 UTC, merged