[tests] Add multiple token owner test
DeFiCh/ain pull request #106
Opened 2020-11-20 08:30 UTC by Bushstar

DeFi tokens can have multiple owners using a multisig address for collateral. The test here creates a 1-of-3 multisig and using that address changes the name three times using each of the multisig addresses. This script is also a demonstration of multiple owner tokens.

2020-11-20 09:05 UTC, ShengguangXiao commented
Can add some failure test cases too?

2020-11-20 09:06 UTC, ShengguangXiao requested changes

2020-11-20 09:06 UTC, ShengguangXiao commented on test/functional/feature_tokens_multisig.py
> +# Copyright (c) 2014-2019 The Bitcoin Core developers
Can change to 2020

2020-11-20 09:18 UTC, Bushstar commented
@ShengguangXiao I'll add a test for 2-of-3 and we can check that 1 single signature will fail and that 2-of-3 works, also check that a single member of the multisig cannot make changes directly.

2020-11-20 12:05 UTC, Bushstar commented
@ShengguangXiao 2-of-3 test case added with above mentioned failure cases.

2020-11-22 14:42 UTC, ShengguangXiao approved these changes

2020-12-01 08:53 UTC, monstrobishi commented
This only touches python tests, merging in

2020-12-01 08:53 UTC, merged