Fix number of totalAuctions in getloaninfo RPC
DeFiCh/ain pull request #1124
Opened 2022-03-01 15:14 UTC by Jouzo

#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:

Calculate totalAuctions by adding each liquidated vault's batch count instead of counting the number of liquidated vaults. 
This will now match the number of open auctions displayed at https://defiscan.live/auctions

2022-03-04 08:08 UTC, bvbfan requested changes

2022-03-04 08:08 UTC, bvbfan commented on src/masternodes/rpc_loan.cpp
> +            totalAuctions += data->batchCount;
```
ForEachVaultAuction([&](const CVaultId& vaultId, const CAuctionData& data)
                                                                     ^^^^
````
Just use it

2022-03-07 08:09 UTC, hidiego approved these changes

2022-03-07 10:16 UTC, bvbfan approved these changes

2022-03-18 04:10 UTC, merged