Prevent bad tx propagation
DeFiCh/ain pull request #137
Opened 2020-12-14 07:00 UTC by bvbfan

This alternative approach to address stalled blockchain issue. It tries to keep mempool consistent on node level and prevent propagation of such a bad tx to other nodes.

2020-12-14 07:15 UTC, Bushstar reviewed
I like the idea. We could first check the TX is a CustomTxType before looping over all mempool TXs. Can you also add a check for accounttoaccount? I found that I can still recreate the issue in block creation with the following.

```
for _ in range(10):
    node.accounttoaccount(account, {destination: "1@DFI"})
    node.accounttoutxos(account, {destination: "1@DFI"})
```

2020-12-14 07:19 UTC, bvbfan commented
`NotAllowedToFail` does not include `accounttoaccount` if you ask me it should.

2020-12-14 08:01 UTC, monstrobishi approved these changes

2020-12-14 08:30 UTC, monstrobishi requested changes

2020-12-14 08:30 UTC, monstrobishi commented on src/validation.cpp
> +                assert(res.ok || !(res.code & CustomTxErrCodes::Fatal)); // inconsistent mempool
don't assert here, reject tx instead

2020-12-15 13:15 UTC, ShengguangXiao approved these changes

2020-12-15 23:12 UTC, merged