Cleanup token migration on attributes
DeFiCh/ain pull request #2356
Opened 2023-08-19 04:16 UTC by prasannavl

## Summary

- Moves DST creation to lower abstractions.
- Simplify codepath removing higher level checks

## Implications

- Storage
  - [x] Database reindex required
  - [ ] Database reindex optional
  - [ ] Database reindex not required
  - [ ] None

- Consensus
  - [ ] Network upgrade required
  - [ ] Includes backward compatible changes
  - [ ] Includes consensus workarounds
  - [x] Includes consensus refactors
  - [ ] None

2023-08-19 05:16 UTC, Bushstar approved these changes

2023-08-19 07:11 UTC, Jouzo approved these changes

2023-08-19 15:19 UTC, sieniven commented on src/masternodes/tokens.cpp
> +                    return Res::Err("Error creating DST20 token: %s", result.reason);
Extra indentation here

2023-08-19 15:19 UTC, sieniven approved these changes

2023-08-21 09:01 UTC, sieniven requested changes

2023-08-21 09:01 UTC, sieniven commented on src/masternodes/govvariables/attributes.cpp
> -                        }
It seems like shifting the ffi call to create dst20 tokens from here into CreateToken in the custom view will mean that the creation of dst20 tokens are no longer done on genesis block, but only on create token or create poolpairs or create loan tokens.

2023-08-21 13:53 UTC, sieniven submitted a review, later dismissed

2023-08-21 13:57 UTC, Jouzo submitted a review, later dismissed

2023-08-21 20:44 UTC, merged