evm: Add next block baseFeePerGas in `eth_feeHistory` output
DeFiCh/ain pull request #2390
Opened 2023-08-29 02:31 UTC by shohamc1

2023-08-29 02:44 UTC, canonbrother requested changes

2023-08-29 02:44 UTC, canonbrother commented on lib/ain-evm/src/block.rs
> +            .get_block_by_number(&(first_block + U256::one()))?
can you test if the first_block == latest_block?

2023-08-30 00:23 UTC, canonbrother commented on test/functional/feature_evm_rpc_fee_history.py
> +                    # "maxPriorityFeePerGas": hex(y), # <-- too-many-eth-txs-by-sender
edge case

2023-08-30 00:24 UTC, canonbrother commented on lib/ain-evm/src/block.rs
> +        // TODO(): b.hash -> b.number
todo

2023-08-30 00:28 UTC, canonbrother commented on lib/ain-evm/src/block.rs
> +            .get_block_by_number(&(first_block + U256::one()))?
resolved at https://github.com/DeFiCh/ain/pull/2390/commits/e8243fb9d8e2baacf2a72758083a40fb946a7d2c

2023-08-30 02:44 UTC, canonbrother commented on test/functional/feature_evm_rpc_fee_history.py
> +                    # "maxPriorityFeePerGas": hex(y), # <-- too-many-eth-txs-by-sender
64 txs is maximum in mempool for the same sender

2023-08-30 03:03 UTC, shohamc1 commented on lib/ain-evm/src/block.rs
> +        // TODO(): b.hash -> b.number
Good catch, thank you.

2023-09-04 03:34 UTC, merged