Lazy rewards redistribution
DeFiCh/ain pull request #279
Opened 2021-03-10 15:03 UTC by bvbfan

/kind feature

I plan to run it in real sync, i have another idea using undos, probably will give a try in another repo. For now we have pool commissions updates on every block, we can fork out by next hard fork. Account rewards are updated before every addition/subtract, optionally we can do it before subtraction only. 

Fixes https://github.com/cakedefi/defichain-private/issues/347

2021-03-11 09:03 UTC, uzyn reviewed
Great work @bvbfan 

Let's test it on testnet or devnet and run some LM with rewards for a couple of weeks. Would be interesting to see how well it performs.

2021-03-11 10:48 UTC, ShengguangXiao commented
So this change need to clear all the DB files and sync from genesis block?  @bvbfan

2021-03-11 11:40 UTC, bvbfan commented
Yep, it should tell that DB is incompatible. I'll resolve the conflicts and will investigate on failing tests.

2021-03-11 12:10 UTC, ShengguangXiao requested changes, later dismissed

2021-03-11 12:10 UTC, ShengguangXiao commented on src/masternodes/mn_checks.h
> +class CGouvernanceMessage {
This should be `CGovernanceMessage`

2021-03-23 10:09 UTC, ShengguangXiao commented
Try to do a clean sync with testnet, but failed in between.
```
2021-03-23T08:40:42Z Synchronizing blockheaders, height: 296669 (~100.00%)
2021-03-23T08:40:51Z Synchronizing blockheaders, height: 296670 (~100.00%)
2021-03-23T08:40:55Z UpdateTip: new best=0e16ff6d957c673ff766b02e011b491fe6537c319afe8efe8dd96d3bdf3c7ebf height=16981 version=0x20000000 log2_work=67.813508 tx=17054 date='2020-10-27T21:16:57Z' progress=0.044829 cache=4.6MiB(34004txo)
2021-03-23T08:41:15Z Synchronizing blockheaders, height: 296671 (~100.00%)
2021-03-23T08:41:16Z UpdateTip: new best=be3b6fd88ef5c4f5ce5296de5dafc643f875e79d465feb34070e64c7e246cb96 height=30045 version=0x20000000 log2_work=68.62052 tx=30192 date='2020-11-02T12:44:07Z' progress=0.079365 cache=8.2MiB(60178txo)
2021-03-23T08:41:16Z Synchronizing blockheaders, height: 296672 (~100.00%)
2021-03-23T08:41:21Z Synchronizing blockheaders, height: 296673 (~100.00%)
2021-03-23T08:41:23Z skipped tx a192ff4b9ae9b71a74506e0a0f99611840e9253f8056ae7915b4971357ac5658: UpdatePoolPairTx: CDataStream::read(): end of data: iostream error
2021-03-23T08:41:23Z skipped tx 407091d6013f3cae897a3c15af8c032ee21ffe63a134e5144cd0a3cc93bc2397: UpdatePoolPairTx: CDataStream::read(): end of data: iostream error
2021-03-23T08:41:23Z skipped tx f2c2188fe63fe983a510ce82daf78725810bc90f68fd61ba68fb9499e06334b0: UpdatePoolPairTx: CDataStream::read(): end of data: iostream error
2021-03-23T08:41:23Z skipped tx 846457d09e6cd2b3362d69f479489d9f33ef64cc388d5e64cef45088a203c16c: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:41:23Z skipped tx a0aedcb58362c9b2e7c606d925d42798d37b1f5a9a291df3912859489cd2708e: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:41:27Z skipped tx b33053c874275cdf1962e66086b03161a0698af0ddea69847f4d3d2b1b0775e7: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:41:27Z Synchronizing blockheaders, height: 296674 (~100.00%)
2021-03-23T08:41:37Z UpdateTip: new best=35b7d28fcf707053ea21d7fee2e9cea932d57dac941e457f154404686d1baf9c height=43112 version=0x20000000 log2_work=69.135927 tx=43426 date='2020-11-08T04:07:58Z' progress=0.114152 cache=11.4MiB(86352txo)
2021-03-23T08:41:39Z Synchronizing blockheaders, height: 296675 (~100.00%)
2021-03-23T08:41:42Z skipped tx 6a107f1e94f801ef3ce0ad451e44704382d67a683436c69cb81e23c47da22eb1: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:41:42Z skipped tx 1d5ffabb901b5b88aab18d23392f8463a578b7c90a9210095725a3abb2ab5a4c: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:41:42Z skipped tx 09e88e570dad1c2bc34d204bbbf42b99e02d48422a13c42da1720d983a70f17b: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:41:42Z skipped tx 8ed2cd4b86468a21b90747cb1db4bb2d010bb449c1a13c3641454b54d2bbd289: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:41:42Z skipped tx 5b62836449c2fe0af70440ac159448cb4917a760a0ee781abc6aa6dca76e5561: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:41:42Z skipped tx 721f795b0609b0cd5e4df9ccb8b12d0ea87d0e1508b094c4008533bff3a8c8b7: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:41:42Z skipped tx d22ab8ee88b0a1e8ea0d7ede0d6cfdbac1da89bcff82c1605e2dd25cb1dc26ca: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:41:42Z skipped tx b0d050389db821ffc85ee4c55b812ff4c333ed40fdcdb086f00282be3deaa19c: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:41:42Z skipped tx 91e792d97472a2130851d502295de633d551b3c74b65609ff4b7e050a5c1026f: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:41:42Z skipped tx 965f11f9ac0c8cae37d0e58cdade6eb8531668e6f64a077a538eb453bf146544: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:41:42Z skipped tx 7d0e54b4d896a794bbc999ade574b0a6d2ce39c974b6bd7f84d5172a8f60b193: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:41:46Z Pre-allocating up to position 0x400000 in rev00000.dat
2021-03-23T08:41:50Z Synchronizing blockheaders, height: 296676 (~100.00%)
2021-03-23T08:41:58Z UpdateTip: new best=7840323a4fc08c5766d55067a20895d2478aa08f277f22fa716a839d8fc014ff height=52549 version=0x20000000 log2_work=69.414301 tx=53050 date='2020-11-12T04:55:35Z' progress=0.139450 cache=13.7MiB(105269txo)
2021-03-23T08:41:58Z skipped tx 457e6a14ccee11160d68af4890ca2a6bc92d09631268b47780011a270557f93b: AddPoolLiquidityTx: amount 9459364810 is less than 10000000000
2021-03-23T08:41:59Z skipped tx eee2ef51bc6923af65a6e90203fcbb7c0b735cd461ec8187265ca93033115beb: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:41:59Z skipped tx 610a25838c2b565f42355fa9be7c6ccd8562e0274327dbba0f92da9de915f7b8: RemovePoolLiquidityTx: amount 82179427 is less than 82465255
2021-03-23T08:41:59Z skipped tx 293dbcf4a2497dab24cb16adb0b38e820874d016efbd94d250f3f9222ea3f246: RemovePoolLiquidityTx: amount 41089488 is less than 41089604
2021-03-23T08:42:18Z Pre-allocating up to position 0x4000000 in blk00000.dat
2021-03-23T08:42:19Z UpdateTip: new best=920fe796d530b002945e9f9f7fed43cd8be4c164e89473d2f88e089df50651c8 height=64014 version=0x20000000 log2_work=69.702782 tx=64621 date='2020-11-17T04:45:01Z' progress=0.169866 cache=17.3MiB(128243txo)
2021-03-23T08:42:24Z Pre-allocating up to position 0x600000 in rev00000.dat
2021-03-23T08:42:25Z skipped tx 098331875da79cc4984753774c00440bec4ab386a0d8dba2b8de823b600d6ab1: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:42:27Z skipped tx e249f6e5773f7b998e6345721a99624c683a59800ff5f32ab253a7ce3dbbca8f: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:42:29Z skipped tx ef73fffe1ca8318a34a474f1e72514284f7b0f332781e184c189a13d06d1152f: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:42:30Z skipped tx 6c8eaa51142b069305e07aea0ee247a467f1fc7d1378428005b8034e069e8cda: AccountToAccountTx: amount 0 is less than 119632800
2021-03-23T08:42:30Z skipped tx 9dbd8e2f2f331e0d314968baedaf49065e45fbd0316c95e8e1e02548437a76f4: AccountToAccountTx: amount 0 is less than 119632800
2021-03-23T08:42:30Z skipped tx 4f5f620484e5359eafb9fe799b568a59ca75202bfe6aa1546c54820c99889437: AccountToAccountTx: amount 0 is less than 119632800
2021-03-23T08:42:34Z skipped tx 2578a1330f3a74f3c465766909913bcf5fbd97e7ff63ac85be19dffef5040ce8: RemovePoolLiquidityTx: amount 0 is less than 1000000000
2021-03-23T08:42:36Z skipped tx c8e28815eab3d8b0a48baa7c9d42922ca916f1ecf9f35e0da878d99f27ccf8d6: RemovePoolLiquidityTx: amount 37590248 is less than 42048966
2021-03-23T08:42:37Z skipped tx d4fd57281f72a8533a9b9c2781e4b9aac277218619ba35bf8fce3e115e106a4a: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:42:37Z skipped tx 53f8759c3f4d7d2c4c217c89d00e3d92f1c162a09d673f545d7e57fd87252d1f: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:42:37Z skipped tx 9af9dac16edc70a1337526d2f761bc3a1b48690fe136c9a61626656f5fd874e5: AddPoolLiquidityTx: amount 461486577 is less than 461491190
2021-03-23T08:42:37Z skipped tx bcac69c321db4203073e2066bd602e1ffc878b8e73e1a2a41ec8c1fdc8f673ef: AddPoolLiquidityTx: amount 449005795480 is less than 461491188919
2021-03-23T08:42:38Z skipped tx 7fccb4f541d8bd952463f09d01575c184d100c719265165603f439034977663f: RemovePoolLiquidityTx: amount 0 is less than 269113084
2021-03-23T08:42:38Z skipped tx f314d0a8fc4a26e1a2bee20e741e1ed0984be3df86d6c57a818a1acb3c2ce7b7: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:42:38Z skipped tx 44badd4561649b6361f4e6ff3fd4854ec971157c23f2e175f07b1cadc50fbd58: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:42:38Z skipped tx ea609ac06952e78aee8820f801956e2c1df96ae43fb28bf239c4ee16fe7554fd: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:42:38Z skipped tx d05093a740e33a16081dd458f142e883277f24431eb8efb73c9cb5d141b625a3: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:42:38Z skipped tx b15b4ade7a131b82b15b5aa839d7fdb44628b2499e3fb40a3bfb64e71deb85b0: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:42:38Z skipped tx bb4dcacd5169b46b1a5f59dc0760b657fc4f16881f8a1e5d491be48ed5a9ac5c: PoolSwapTx: Pool trading is turned off!
2021-03-23T08:42:38Z skipped tx 5e3b3d896cb63f75e38b50506df39ce2183bee176e53e9a0fe28be229c3aa20a: PoolSwapTx: Pool trading  [...]

2021-03-23 11:50 UTC, bvbfan commented
@ShengguangXiao it looks like some serialization issue `CDataStream::read(): end of data: iostream error` will investigate, thanks for test.

2021-03-23 11:56 UTC, bvbfan commented
Quick update:
```
struct CUpdatePoolPairMessage {
    DCT_ID poolId;
    bool status;
    CAmount commission;
    CScript ownerAddress;
    CBalances rewards;
};
```
I change serialization of `DCT_ID` and it's not same as pervious, now it's `VARINT` compared to raw integer. Will update after sync on testnet.

2021-03-29 06:14 UTC, monstrobishi approved these changes

2021-04-08 08:06 UTC, ShengguangXiao commented
I can sync with testnet using this branch from a clean data folder now.

2021-04-19 07:38 UTC, merged