Fix/prevent reverts
DeFiCh/ain pull request #408
Opened 2021-05-20 07:43 UTC by bvbfan

/kind fix

#### What this PR does / why we need it:

Including merkle root of account system we don't need to revert chain to last checkpoint / anchor since we validate ongoing changes.

2021-05-20 08:42 UTC, monstrobishi commented on src/validation.cpp
> +                    if (pindexConnect->nHeight < chainparams.GetConsensus().EunosHeight
Does this need to check height? I think we can still encounter problem before EunosHeight

2021-05-20 08:58 UTC, monstrobishi requested changes
We should keep reorg behviour unless we include account system merkle root validation

2021-05-21 06:36 UTC, Bushstar approved these changes

2021-05-21 06:39 UTC, monstrobishi approved these changes

2021-05-21 06:56 UTC, merged