Fix if else using same condition
DeFiCh/ain pull request #466
Opened 2021-06-01 12:12 UTC by ShengguangXiao

#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:

Fix if else using same condition

#### Which issue(s) does this PR fixes?:

Fixes # https://github.com/DeFiCh/ain/issues/463

#### Additional comments?:

2021-06-01 14:53 UTC, bvbfan approved these changes

2021-06-01 14:53 UTC, bvbfan commented on src/masternodes/rpc_customtx.cpp
>          auto token = mnview.GetToken(obj.idToken);
Can you add check for token presence, even in rpc we wouldn't crash.

2021-06-02 15:11 UTC, Mixa84 requested changes

2021-06-07 15:58 UTC, ShengguangXiao commented on src/masternodes/rpc_customtx.cpp
> +            }
@Mixa84 Updated, please review again.

2021-06-09 15:34 UTC, Mixa84 approved these changes

2021-06-10 10:41 UTC, merged