v1.8.0
DeFiCh/ain pull request #530
Opened 2021-06-14 10:38 UTC by Bushstar

2021-06-14 10:39 UTC, Mixa84 approved these changes

2021-06-14 10:44 UTC, bvbfan requested changes

2021-06-14 10:44 UTC, bvbfan commented on src/chainparams.cpp
> +        consensus.FortCanningHeight = static_cast<int>(height);
Remove

2021-06-14 14:11 UTC, Bushstar commented on src/chainparams.cpp
> +        consensus.FortCanningHeight = static_cast<int>(height);
Thanks.  Left over from EunosPaya.

2021-06-14 14:26 UTC, bvbfan approved these changes

2021-07-15 11:31 UTC, prasannavl approved these changes

2021-07-15 13:54 UTC, merged