Apply token filter to rewards in history
DeFiCh/ain pull request #557
Opened 2021-06-22 06:47 UTC by bvbfan

/kind fix

#### What this PR does / why we need it:

It filters rewards by token in account history

2021-06-22 07:22 UTC, monstrobishi requested changes
Ensure no external services rely on existing behavior before merging

2021-06-28 07:58 UTC, uzyn commented
@bvbfan can you provide some writeups on what RPCs does this break and sample old and new outputs please?

2021-07-02 11:05 UTC, bvbfan commented
It does not break anything, it can return less results, it means when you set token filter BTC will not get rewads in DFI

2021-07-06 13:09 UTC, Bushstar approved these changes

2021-07-06 13:09 UTC, merged