Send from UTXOs, do not subtract fee from amount
DeFiCh/ain pull request #559
Opened 2021-06-23 09:53 UTC by Bushstar

Resolves https://github.com/DeFiCh/ain/issues/552

2021-06-23 11:40 UTC, bvbfan approved these changes

2021-06-24 08:13 UTC, uzyn requested changes
Please add a unit test for this.

2021-06-28 09:06 UTC, uzyn commented
@hidiego please assist to add unit test for this PR.

2021-07-01 08:01 UTC, bvbfan approved these changes

2021-07-02 10:55 UTC, merged