Updated the code to generate blocks for the given address.
DeFiCh/ain pull request #646
Opened 2021-07-29 21:02 UTC by surangap

#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:
will generate to the given address. currently, it is generated to the first masternode
#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2021-07-30 06:42 UTC, bvbfan requested changes

2021-07-30 06:42 UTC, bvbfan commented on src/rpc/mining.cpp
> +    }
Just use `count`
```
if (myAllMNs.count(passedID)) {
    myID = passedID;
} else {
    myID = myAllMNs.begin()->first;
}
```

2021-07-30 12:51 UTC, bvbfan approved these changes

2021-08-02 11:34 UTC, ShengguangXiao commented on src/rpc/mining.cpp
> +#include <utility>
These two includes have no use

2021-08-02 11:35 UTC, ShengguangXiao commented on test/functional/rpc_getmininginfo.py
> +        self.restart_node(1, ['-gen','-dummypos=0', '-rewardaddress=' + operators[1]] +
Add blank after ,

2021-08-02 11:35 UTC, ShengguangXiao commented
The logic looks good, i just left two minor comments

2021-08-03 01:32 UTC, ShengguangXiao submitted a review, later dismissed

2021-08-03 08:33 UTC, bvbfan submitted a review, later dismissed

2021-08-03 22:52 UTC, prasannavl requested changes
Just the one minor nit pick, and it's good to merge. Thanks!

2021-08-03 22:52 UTC, prasannavl commented on src/rpc/mining.cpp
> +    CKeyID passedID = destination.which() == PKHashType ? CKeyID(*boost::get<PKHash>(&destination)) :
Could you please break this line into a switch statement instead? That would be far more readable and way easier to maintain. Everything else looks good.

2021-08-04 09:41 UTC, prasannavl commented
Perfect. Looks good now, thanks!

2021-08-04 10:15 UTC, prasannavl approved these changes

2021-08-04 10:16 UTC, merged