Take loan feature
DeFiCh/ain pull request #700
Opened 2021-08-30 11:48 UTC by Mixa84

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
Initial development on `takeloan` function to "mint" tokens as a loan based on deposited collateral in vault.

#### Which issue(s) does this PR fixes?:

Fixes #671

2021-08-30 13:41 UTC, Mixa84 commented
> So the difference is it may not contain loan tokens ? I don't see reason this function to exist, it's used in `getloan` if there is no loan tokens who cares for collaterals ?

The point was that `CalculateCollateralizationRatio` was not returning anything if there were no loans taken. I wanted to display total collateral value and total loan value. If we don't really need to see how much is in collateral if there is no loan then we can remove this function and I'll use `CalculateCollateralizationRatio`.

2021-08-30 14:55 UTC, hidiego approved these changes

2021-08-30 15:09 UTC, ShengguangXiao commented on src/masternodes/rpc_loan.cpp
> +    ret.pushKV("Loan value (USD)",ValueFromAmount(totalLoans));
Seems we don't use blanks in our keys.

2021-08-30 15:43 UTC, Mixa84 commented on src/masternodes/rpc_loan.cpp
> +    ret.pushKV("Loan value (USD)",ValueFromAmount(totalLoans));
Forgot, I will correct it.

2021-08-31 09:10 UTC, bvbfan commented
> > So the difference is it may not contain loan tokens ? I don't see reason this function to exist, it's used in `getloan` if there is no loan tokens who cares for collaterals ?
> 
> The point was that `CalculateCollateralizationRatio` was not returning anything if there were no loans taken. I wanted to display total collateral value and total loan value. If we don't really need to see how much is in collateral if there is no loan then we can remove this function and I'll use `CalculateCollateralizationRatio`.

Yep, there is nothing to calculate when there is no loan tokens, it should be the same for `getloan`, there is nothing to return when no loans.

2021-09-01 11:46 UTC, bvbfan requested changes

2021-09-01 11:46 UTC, bvbfan commented on src/masternodes/masternodes.cpp
>      return ret;
Merge this function with main one.

2021-09-01 11:46 UTC, bvbfan commented on src/masternodes/masternodes.h
> +        if (loans.empty()) return 0;
Return `std::numeric_limits<uint32_t>::max` because when only collaterals are in ratio is the higher one.

2021-09-01 11:49 UTC, bvbfan commented
Add `LoanTakeLoanCreationTx` and `LoanTakeLoanVaultKey` to `CheckPrefix` `CLoanView`

2021-09-01 15:46 UTC, bvbfan approved these changes

2021-09-02 04:46 UTC, merged