[WIP] High precision interest calculation
DeFiCh/ain pull request #991
Opened 2021-12-17 20:08 UTC by Mixa84

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
Improves the precision for calculating interest. It will make interest be precise on smaller loan amounts so that it doesn't get rounded to 1 sat and be unfair for small amounts of loans.

#### Which issue(s) does this PR fixes?:

Fixes #984

2021-12-20 07:55 UTC, bvbfan requested changes

2021-12-20 07:55 UTC, bvbfan commented on src/arith_uint256.cpp
> +    return b.GetHex();
That's not look correct, It should have similar code to `uint256::GetHex` here

2021-12-20 07:55 UTC, bvbfan commented on src/arith_uint256.cpp
> +        pn[x] = ReadLE32(a.begin() + x*4);
Here it's wrong, it should copy the lowest not he highest bits, i would prefer similar to `uint256::SetHex` here. Probably it should get bytes count.

2021-12-20 07:55 UTC, bvbfan commented on src/arith_uint256.cpp
> +template std::string base_uint<128>::ToString() const;
It's redundant, the above as well. Explicit template specialization can be based on entire class not on specific function.
`template<> class base_uint<128>;`

2021-12-20 07:55 UTC, bvbfan commented on src/arith_uint256.cpp
> +
Also add `arith_uint128` as type and use it elsewhere.

2021-12-20 07:55 UTC, bvbfan commented on src/masternodes/loan.cpp
> +base_uint<128> TotalInterest(const CInterestRateV2& rate, uint32_t height)
Probably `TotalInterest` can do the ceil

2021-12-23 11:41 UTC, Bushstar commented on src/chainparams.cpp
> +    UpdateHeightValidation("Fork canning new", "-FortCanningHillheight", consensus.FortCanningHillHeight);
lowercase for -fortcanninghillheight

2021-12-23 11:46 UTC, Bushstar commented on src/init.cpp
> +    gArgs.AddArg("-FortCanningHillheight", "Fort Canning New fork activation height (regtest only)", ArgsManager::ALLOW_ANY, OptionsCategory::CHAINPARAMS);
lowercase for -fortcanninghillheight here as well.

2021-12-29 12:43 UTC, bvbfan submitted a review, later dismissed

2021-12-30 09:09 UTC, bvbfan submitted a review, later dismissed

2022-01-11 11:27 UTC, bvbfan approved these changes, later dismissed

2022-01-19 10:10 UTC, bvbfan submitted a review, later dismissed

2022-01-19 15:14 UTC, bvbfan submitted a review, later dismissed

2022-01-21 11:27 UTC, bvbfan approved these changes, later dismissed

2022-01-24 17:20 UTC, prasannavl approved these changes

2022-01-24 17:21 UTC, merged